### ISSUE TITLE
Suppression

### ISSUE THREAD

**Issue by LenaicTerrier** [CRM12/Gobelins-CRM12#1]
Le repo contient les adresses mails de toute la promo CRM13 en clair.
Guillaume a déjà enlevé le fichier avec le commit baf9b35, merci de finir le boulot en supprimant le repo.

Ping : @Aynolor @mr-blond @Frulko @Xanatos38 @Reight

**Comment by Aynolor** [comment]
J'ai supprimé toutes les références au fichier crm13.php. Sauf erreur, le fichier n'apparaît plus dans l'historique. ;-)

**Comment by LenaicTerrier** [comment]
Non mais les url existent bien, 86d24c0 et baf9b35, et toutes les url qui s'y rattachent (blame, raw, diff, etc.)

**Comment by Aynolor** [comment]
J'ai contacté Github pour supprimer le cache, on ne peut rien faire de plus. ;-) ;-)

**Comment by Aynolor** [comment]
Elles renvoient maintenant des 404.
